### PR TITLE
Only list targets relevant to the current OS

### PR DESCRIPTION
**Pull request by Gama11**

### CODE REVIEW

**Comment by ibilon** [comment]
It doesn't work for iOS but for windows/linux/mac if you try to build them on another OS you'll get a cross platform neko build.

**Comment by Gama11** [comment]
I know about that, but I always felt like that's more confusing than helpful.. Do people actually use that in practice? I've only seen people be confused by that, expecting a "real" cross-compiled cpp build (which is reasonable, since "[OS-name]" normally means cpp).

**Comment by ibilon** [comment]
True, there might not be a lot of people using that. If you can't build you most likely can't test.
And neko builds don't have the best performances.

**Comment by Gama11** [comment]
Yeah, I've seen people wonder why their Linux build performs so badly, and they didn't realize it was a Neko build.

**Pull request merged**
